{
 "title": "World of Games",
 "tags": [
  "world-of-games",
  "flask"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Request Rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(flask_http_request_total[1m])",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum[1m]) / rate(flask_http_request_duration_seconds_count[1m])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Total Successful Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_http_request_total{status=\"200\"}",
     "legendFormat": "200 OK"
    }
   ]
  },
  {
   "title": "Total Error Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_http_request_total{status=~\"4..|5..\"}",
     "legendFormat": "Errors"
    }
   ]
  }
 ]
}